/** All helpers page objects may import from `support/web-actions.ts`. Source of truth: packages/web-core/src/web-actions.ts */
export const WEB_ACTION_EXPORTS = [
  "checkWhenVisible",
  "clearWhenVisible",
  "clickOpensNewPage",
  "clickWhenVisible",
  "closePage",
  "doubleClickWhenVisible",
  "expectChecked",
  "expectContainsText",
  "expectCount",
  "expectCountGreaterThan",
  "expectDisabled",
  "expectEnabled",
  "expectFocused",
  "expectHidden",
  "expectSelected",
  "expectText",
  "expectUnchecked",
  "expectValue",
  "expectVisible",
  "fill",
  "fillWhenVisible",
  "getTextWhenVisible",
  "goBack",
  "hoverWhenVisible",
  "longPressWhenVisible",
  "navigateTo",
  "scrollIntoView",
  "scrollIntoViewWhenVisible",
  "selectOptionWhenVisible",
  "takeScreenshot",
  "typeTextWhenVisible",
  "uncheckWhenVisible",
  "waitForHidden",
  "waitForNewPage",
  "waitForVisible",
  "waitMs",
  "webLocator",
] as const;

export const WEB_ACTIONS_IMPORT_BLOCK = `import {
  ${WEB_ACTION_EXPORTS.join(",\n  ")},
} from "../support/web-actions";`;
